--Highest Revenue generated by Year--
WITH release_date_split AS (
    SELECT 
        Release_Date,
        EXTRACT(YEAR FROM Release_Date) AS year, 
        Revenue
    FROM `sample-project-349911.movie_data.movies`
    GROUP BY Release_Date, Revenue
)
SELECT year, SUM(Revenue) as Total_Revenue
FROM release_date_split
GROUP BY year
ORDER BY year; 

--Most Profitable Year on Average--
WITH release_date_split AS (
    SELECT 
        Release_Date,
        EXTRACT(YEAR FROM Release_Date) AS year, 
        SUM(Revenue-Budget_) as Profit
    FROM `sample-project-349911.movie_data.movies`
    GROUP BY Release_Date, Revenue
)
SELECT year, AVG(Profit) as Average_Profit
FROM release_date_split
GROUP BY year
ORDER BY year; 

--Number of movies released each year--
WITH release_date_split AS (
    SELECT 
        Release_date,
        EXTRACT(YEAR FROM Release_Date) AS year, 
    FROM `sample-project-349911.movie_data.movies`
)
SELECT year, COUNT(*) as number_of_movies
FROM release_date_split
GROUP BY year
ORDER BY year;

--Months where Most Revenue was generated--
SELECT 
    EXTRACT(MONTH from Release_Date) as month,
    SUM(Revenue) as total_revenue
FROM `sample-project-349911.movie_data.movies`
GROUP BY month
ORDER BY total_revenue DESC;

--Highest Grossing Movie Genre--
SELECT Genre, MAX (Revenue) as Highest_Grossing
FROM `sample-project-349911.movie_data.movies` 
GROUP BY Genre
ORDER BY MAX (Revenue) DESC;

--Most Profitable Movie Genre--
SELECT Genre, SUM(Revenue-Budget_) as Profit
FROM `sample-project-349911.movie_data.movies`
GROUP BY Genre
ORDER BY Profit DESC;

--Top 10 Directors that generate most Revenue--
SELECT Director__1_, SUM(Revenue) AS Total_Revenue
FROM `sample-project-349911.movie_data.movies`
GROUP BY Director__1_
ORDER BY Total_Revenue DESC
LIMIT 10;

--Most profitable movies of Top billed cast members--
WITH actors_profit AS (
    SELECT Cast__1_, SUM(Revenue - Budget_) AS Total_profit
    FROM `sample-project-349911.movie_data.movies`
    WHERE Cast__1_ IS NOT NULL
    GROUP BY Cast__1_
    ORDER BY Total_profit DESC
    LIMIT 10
)
SELECT a.Cast__1_, m.Movie_Title, (m.Revenue - m.Budget_) as profit
FROM `sample-project-349911.movie_data.movies` m
JOIN actors_profit a ON m.Cast__1_ = a.Cast__1_
ORDER BY a.total_profit DESC, profit DESC;

--Highest revenue by genre for every year--
SELECT 
    year,
    Genre,
    MAX(total_revenue) as highest_revenue
FROM (
    SELECT 
        Genre,
        EXTRACT(YEAR FROM Release_Date) AS year,
        SUM(Revenue) as Total_Revenue
    FROM `sample-project-349911.movie_data.movies`
    GROUP BY Genre, year
)
GROUP BY year, Genre
ORDER BY year;

--Directors and their most popular Genres--
SELECT 
    Director__1_, 
    MAX(CASE WHEN genre_count = max_genre_count THEN genre END) as most_frequent_genre
FROM (
    SELECT 
        Director__1_, 
        genre, 
        COUNT(*) as genre_count, 
        MAX(COUNT(*)) OVER (PARTITION BY Director__1_) as max_genre_count
    FROM `sample-project-349911.movie_data.movies` 
    GROUP BY Director__1_, genre
)
GROUP BY Director__1_
ORDER BY Director__1_
